test:
  api_token: test_key
  search_server: 'http://test.te'
  data_server: 'http://test2.te'
  marker: 12346
  bitly:
    hello: 'world'

development:
  api_token: test_key
  search_server: 'http://test.te'
  data_server: 'http://beta-overmind.jetradar.com'
  marker:
